### create a contact

POST https://contact-book-production-b6ca.up.railway.app/contacts
Content-Type: application/json

{
    "name": "Nikhil",
    "email": "nikhil130@example.com",
    "phone": "9078563214"
  }
### get all contacts
GET https://contact-book-production-b6ca.up.railway.app/contacts?page=1&limit=5

### update contact
PATCH https://contact-book-production-b6ca.up.railway.app/contacts/4
Content-Type: application/json

{
  "name": "Ram",
  "email": "ram10@example.com",
  "phone": "9876543210"
}

### delete contact

DELETE http://localhost:5000/contacts/16
